export const CACHE_TAGS = {
    NAVBAR: 'navbar',
    SETTINGS: 'settings',
    FOOTER: 'footer',
    ARTICLES: 'articles',
    FEATURED_ARTICLES: 'featured_articles',
    HOMEPAGE: 'homepage',
    ABOUTPAGE: 'about_page',
    CONTACTPAGE: 'contact_page',
    COURSEPAGE: 'course_page',
    FACULTYPAGE: 'faculty_page',
    NOTICESPAGE: 'notices_page',
    BLOGSPAGE: 'blogs_page',
    TEACHERS: 'teachers',
    NOTICES: 'notices',
    CATEGORIES: 'categories',
    COURSES: 'courses',
    PAGES: 'pages',
    STUDENT_RANKS: 'student_ranks',
    STUDENT_RANK_CATEGORIES: 'student_rank_categories',
    LOCATIONS: 'locations',
} as const;
